/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // deveLogSidebar: [{ type: "autogenerated", dirName: "develog" }],

  a11ySidebar: [{ type: "autogenerated", dirName: "develog/a11y" }],
  deveLogSidebar: [
    "develog/index",
    {
      type: "doc",
      label: "A11y",
      id: "develog/a11y/index",
    },
  ],
  r1250rsSidebar: [
    { type: "autogenerated", dirName: "lifelog/r1250rs" },
  ],

  lifeLogSidebar: [
    "lifelog/index",
    {
      type: "doc",
      label: "R1250RS",
      id: "lifelog/r1250rs/index",
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
